live:
    scheme: <%= live_ftp_scheme %>
    host: <%= live_ftp_host %>
    port: <%= live_ftp_port %>
    user: <%= live_ftp_user %>
    pass: <%= live_ftp_pass %>
    check: true
    exclude: ["dploy.yaml","*.sublime-*","sftp-conf*",".DS_Store",".remote-sync.json","package.json","composer.*","webpack.*","/src/**", ".git*", "phploy.ini"]
    include:
        "files/theme_<%= theme %>/**" : "files/theme_<%= theme %>/"
    path:
        local: /
        remote: <%= live_ftp_path_remote %>

live_vendor:
    scheme: <%= live_ftp_scheme %>
    host: <%= live_ftp_host %>
    port: <%= live_ftp_port %>
    user: <%= live_ftp_user %>
    pass: <%= live_ftp_pass %>
    check: true
    include:
        "**" : "/"
    path:
        local: /vendor
        remote: <%= live_ftp_path_remote %>/vendor

<% if(deployToRemoteSync){ %>preview:
    scheme: <%= preview_ftp_scheme %>
    host: <%= preview_ftp_host %>
    port: <%= preview_ftp_port %>
    user: <%= preview_ftp_user %>
    pass: <%= preview_ftp_pass %>
    check: true
    exclude: ["dploy.yaml","*.sublime-*","sftp-conf*",".DS_Store",".remote-sync.json","package.json","composer.*","webpack.*","/src/**", ".git*", "phploy.ini"]
    include:
        "files/theme_<%= theme %>/**" : "files/theme_<%= theme %>/"
    path:
        local: /
        remote: <%= preview_ftp_path_remote %>

preview_vendor:
    scheme: <%= preview_ftp_scheme %>
    host: <%= preview_ftp_host %>
    port: <%= preview_ftp_port %>
    user: <%= preview_ftp_user %>
    pass: <%= preview_ftp_pass %>
    check: true
    include:
        "vendor/**" : "vendor/"
    path:
        local: /
        remote: <%= preview_ftp_path_remote %>
<% } %>